Resources:

- [Kaggle kernel Only clarification](https://www.kaggle.com/c/jigsaw-unintended-bias-in-toxicity-classification/discussion/87719#latest-516430)
- https://www.topbots.com/most-important-ai-nlp-research/#ai-nlp-paper-2018-1
- https://aclweb.org/anthology/K18-1030
- https://medium.com/@jatinmandav3/opinion-mining-sometimes-known-as-sentiment-analysis-or-emotion-ai-refers-to-the-use-of-natural-874f369194c0
- https://arxiv.org/pdf/1810.04805.pdf
- [Navigate Virtual Maze - sample project](https://github.com/udacity/machine-learning/blob/master/projects/capstone/report-example-3.pdf)
- https://github.com/google/sentencepiece
- [Profanity check](https://github.com/vzhou842/profanity-check)
- [The transformer, open ai, bert](http://jalammar.github.io/illustrated-bert/)
- [Colab BERT End-2-End](https://colab.research.google.com/drive/12-7OQIi8YJX5tZBbLDgbcCxcyOT6oWHL)
- [ROC AUC Curve - Google ML](https://developers.google.com/machine-learning/crash-course/classification/roc-and-auc)
- [Spacey, Prodigy](https://explosion.ai/)
- [Paper on training language models with Deep NN of different sizes](https://pdfs.semanticscholar.org/a177/45f1d7045636577bcd5d513620df5860e9e5.pdf)
- [onnx models](https://github.com/onnx)
- [Fasttext](https://keras.io/examples/imdb_fasttext/)
- [Attention is all you need - Transformer paper](https://arxiv.org/pdf/1706.03762.pdf)
- [Transformers - Attention intuition](https://towardsdatascience.com/transformers-141e32e69591)
- [BERT Discussion Video on YouTube (Rachel - Kaggle)](https://www.youtube.com/watch?v=IF6xV0RI91s)
- [GLUE BENCHMARK](https://gluebenchmark.com/submission/QBStnIRNNwP5gULgPuBjzK3tJqz2/-LbP6zV9cmUAvtgpRi1d)
- [Speed of Hierarchical Softmax](https://www.quora.com/What-is-hierarchical-softmax)
- [LSTM](http://colah.github.io/posts/2015-08-Understanding-LSTMs/)
- [Different activation functions](https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6)
- [Universal Language Model Fine Tuning - Jeremy Howard transfer learning](https://aclweb.org/anthology/P18-1031)
- [Bias causing deaths](https://youtu.be/hkBa9pU-H48?t=7455)
- [Deep learning book](http://www.deeplearningbook.org/contents/convnets.html)
- [Would you dare to go with two features](https://www.kaggle.com/c/dont-overfit-ii/discussion/90216)
- [Understanding LSTM network - Chris Olah (mentioned by Andrew Ng)](https://colah.github.io/posts/2015-08-Understanding-LSTMs/)

Prediction bias is a quantity that measures how far apart those two averages are. That is:

`"average of predictions" should ≈ "average of observations"`


#### TODO list:

- ~~Check rubric~~
- ~~Check tahn~~
- ~~Weighted BCE Loss~~
- ~~install pytorch locally~~
- ~~Seed notebook for repeated experiment~~
- Learn Pytorch
- Take a subset of the data for each category 
- Train on that
- ~~Define benchmark~~
- ~~Improve on benchmark~~
- check prediction bias based on average of prediction = average of observation
- Check garbage collection with inheritance
- Fix references in Capstone project





In [366]:
import torch
from torch import nn
from torch.utils import data
from torch.nn import functional as F
import numpy as np
from torch.autograd import Variable

In [357]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()

        self.l1 = nn.Linear(5, 2)
        self.s = nn.Sigmoid()

    def forward(self, x):
#         x = embed(x)
#         x = x.view(x.size(0), -1)
#         print(len(x))
        x = self.l1(x)
        x = self.s(x)

        return x

net = Net()
print(net)

Net(
  (l1): Linear(in_features=5, out_features=2, bias=True)
  (s): Sigmoid()
)


In [358]:
x = np.zeros([1000,5])
samples = np.random.choice(999, 100)
y = np.zeros([1000, 1])

In [359]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [360]:
for s in samples:
    i = np.random.choice(5, 1)
    x[s][i] = 1
    y[s] = 1    

In [361]:
t_x = torch.tensor(x, dtype = torch.float32)
t_y = torch.tensor(y, dtype = torch.long)  # a dummy target, for example
# target = target.view(5, -1)  # make it the same shape as output



t_y[0:10]

tensor([[0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]])

In [363]:
# train_loader = torch.utils.data.DataLoader(t_x, batch_size=500, shuffle=True)


optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
criterion = nn.CrossEntropyLoss()

for a in range(1000):
    net.train()
    
#     for data in train_loader:
#     print((data.size()))
    output = net(t_x)
#     output = torch.squeeze(output)
#     print(f'output {output}', end="\n")
    print(output.shape)
    print(output)
    
    loss = criterion(output, t_y)
#     print(f'loss {loss}', end="\n")
    sys.stdout.flush()    
    optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()

torch.Size([1000, 2])
tensor([[0.5873, 0.5889],
        [0.5873, 0.5889],
        [0.6229, 0.5079],
        ...,
        [0.5873, 0.5889],
        [0.5873, 0.5889],
        [0.5873, 0.5889]], grad_fn=<SigmoidBackward>)


RuntimeError: multi-target not supported at /Users/soumith/mc3build/conda-bld/pytorch_1549593514549/work/aten/src/THNN/generic/ClassNLLCriterion.c:21

In [305]:
print(loss)

tensor(0.0871, grad_fn=<MseLossBackward>)


In [367]:
criterion = nn.CrossEntropyLoss()

output = Variable(torch.randn(10, 120).float())
target = Variable(torch.FloatTensor(10).uniform_(0, 120).long())

loss = criterion(output, target)


In [370]:
target

tensor([ 43,  52,  17,  20,  34,  94, 119,  45,  66, 116])

In [371]:
output

tensor([[-0.9321,  0.5197, -0.0831,  ...,  0.4498,  2.5436, -0.2508],
        [ 1.9875,  0.3367,  0.2426,  ..., -1.1863,  2.0092, -0.4716],
        [-1.3475,  0.7161,  0.4707,  ...,  0.5491, -0.5342, -0.1399],
        ...,
        [ 0.6612,  1.6143, -1.5574,  ..., -0.7925, -0.3296, -0.8932],
        [ 1.2284,  0.7455,  0.0149,  ...,  0.3880, -0.7877, -1.4719],
        [ 0.7115,  0.1199,  0.1454,  ..., -1.6000, -0.8070,  1.3111]])

In [26]:
# Author: Robert Guthrie

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [35]:
lstm = nn.LSTM(3, 5)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5

# initialize the hidden state.
hidden = (torch.randn(1, 1, 5),
          torch.randn(1, 1, 5))
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)

In [36]:
inputs

[tensor([[-1.7126, -0.2720,  1.4122]]),
 tensor([[ 0.9275,  0.3314, -0.3171]]),
 tensor([[ 0.6291, -2.0567,  0.6842]]),
 tensor([[-0.5331, -0.1527, -0.6993]]),
 tensor([[0.4899, 0.3985, 0.7510]])]

In [37]:
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 5), torch.randn(1, 1, 5))  # clean out hidden state
out, hidden = lstm(inputs, hidden)
print(out)
print(hidden)

tensor([[[-0.5337, -0.4164, -0.2098, -0.4408, -0.3760]],

        [[-0.1640, -0.0382, -0.0851, -0.1615, -0.1412]],

        [[-0.0429,  0.0633,  0.0084, -0.0885, -0.1745]],

        [[-0.0760,  0.1913, -0.0569, -0.1711, -0.1431]],

        [[-0.2272,  0.0704, -0.0211, -0.1635, -0.0683]]],
       grad_fn=<StackBackward>)
(tensor([[[-0.2272,  0.0704, -0.0211, -0.1635, -0.0683]]],
       grad_fn=<StackBackward>), tensor([[[-0.3893,  0.1426, -0.0657, -0.4996, -0.1493]]],
       grad_fn=<StackBackward>))


$    \begin{array}{ll} \\
        i_t = \sigma(W_{ii} x_t + b_{ii} + W_{hi} h_{(t-1)} + b_{hi}) \\
        f_t = \sigma(W_{if} x_t + b_{if} + W_{hf} h_{(t-1)} + b_{hf}) \\
        g_t = \tanh(W_{ig} x_t + b_{ig} + W_{hg} h_{(t-1)} + b_{hg}) \\
        o_t = \sigma(W_{io} x_t + b_{io} + W_{ho} h_{(t-1)} + b_{ho}) \\
        c_t = f_t c_{(t-1)} + i_t g_t \\
        h_t = o_t \tanh(c_t) \\
    \end{array}
    $

In [38]:
a, b = (1, 2, 4)

ValueError: too many values to unpack (expected 2)